# _config.yml

# Site settings
title: My Jekyll Site
description: A simple Jekyll site hosted on GitHub Pages
baseurl: ""
url: "https://sdoganata.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  posts:
    output: true
